{
 "title": "Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "juju_application",
    "label": "Application",
    "query": {
     "query": "label_values(flask_requests{},juju_application)"
    }
   },
   { "name": "filter", "label": "Search" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(50,sum by(path, status) (count_over_time({juju_application=\"$juju_application\"} != `haproxy/httpchk`!= `/_status` |= `$filter` |  pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\"\" | status != \"404\"  | status=~\"4..|5..\"  [$__range])))"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({juju_application=\"$juju_application\"} != `haproxy/httpchk` |= `$filter` |  pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 27, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{juju_application = \"$juju_application\"}  != \"_status\" |= \"$filter\" | pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\"\""
    }
   ]
  },
  {
   "title": "Paths",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "topk(50,sum by(path) (count_over_time({juju_application=\"$juju_application\"} != `haproxy/httpchk`!= `/_status` |= `$filter` |  pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "User agents",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "topk(50,sum by(user_agent) (count_over_time({juju_application=\"$juju_application\"} != `haproxy/httpchk`!= `/_status` |= `$filter` |  pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\"\" [$__range])))"
    }
   ]
  }
 ]
}