name: Deploy

on:
  workflow_call:
    inputs:
      # Used for pack_release workflow
      charm_name:
        required: true
        type: string
      channel:
        required: true
        type: string
      force_charm_build:
        required: false
        default: false
        type: boolean
      # Used for juju_deploy_ps6 workflow
      juju_controller_name:
        required: false
        type: string
      juju_model_name:
        required: false
        type: string
      # Used to select the deployment method (juju vs terraform)
      deploy_method:
        required: false
        default: 'juju'
        type: string
      # Used for terraform_apply workflow (deploy_method = terraform)
      terraform_dir:
        required: false
        default: ''
        type: string
      terraform_github_repo:
        required: false
        type: string
        default: "canonical/webteam-terraform-plans"
      vault_model_name:
        required: false
        type: string
      iam_group:
        required: false
        type: string
        default: "canonical-webdesign"
      # Common variables for GH environment usage
      environment:
        required: false
        default: ''
        type: string
      environment_url:
        required: false
        default: ''
        type: string
    secrets:
      # Used for pack_release workflow
      CHARMHUB_TOKEN:
        required: true
      # Used for juju_deploy_ps6 & terraform_apply workflows
      VAULT_APPROLE_ROLE_ID:
        required: true
      VAULT_APPROLE_SECRET_ID:
        required: true
      # Optionally used for terraform_apply workflow when using a custom repo for the terraform configuration
      TERRAFORM_REPO_SSH_KEY:
        required: false

jobs:
  validate:
    name: Validate inputs
    runs-on: ubuntu-latest
    steps:
      # Cancel the full job if deploy_method is not supported
      - name: Validate deploy_method
        run: |
          if [ "${{ inputs.deploy_method }}" != "juju" ] && [ "${{ inputs.deploy_method }}" != "terraform" ]; then
            echo "deploy_method must be 'juju' or 'terraform'"
            exit 1
          fi

  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      juju_controller_name: ${{ steps.setup-vars.outputs.juju_controller_name }}
      juju_model_name: ${{ steps.setup-vars.outputs.juju_model_name }}
    steps:
      - name: Set up vars
        id: setup-vars
        run: |
          export JUJU_CONTROLLER_NAME_INPUT=${{ inputs.juju_controller_name }}
          export JUJU_MODEL_NAME_INPUT=${{ inputs.juju_model_name }}
          echo "juju_controller_name=${JUJU_CONTROLLER_NAME_INPUT:-${{ vars.JUJU_CONTROLLER_NAME }}}" >> $GITHUB_OUTPUT
          echo "juju_model_name=${JUJU_MODEL_NAME_INPUT:-${{ vars.JUJU_MODEL_NAME }}}" >> $GITHUB_OUTPUT

  pack-and-release:
    name: Pack and Release
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/pack_release.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      environment: ${{ inputs.environment }}
      force_charm_build: ${{ inputs.force_charm_build }}
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

  deploy-ps6:
    name: Deploy with Juju CLI
    needs: [setup, pack-and-release]
    if: always() && !failure() && !cancelled() && inputs.deploy_method == 'juju'
    uses: ./.github/workflows/juju_deploy_ps6.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      resource_name: ${{ needs.pack-and-release.outputs.resource_name }}
      resource_revision_number: ${{ needs.pack-and-release.outputs.resource_revision_number }}
      juju_controller_name: ${{ needs.setup.outputs.juju_controller_name }}
      juju_model_name: ${{ needs.setup.outputs.juju_model_name }}
      environment: ${{ inputs.environment }}
      environment_url: ${{ inputs.environment_url }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  deploy-ps7:
    name: Deploy with Terraform
    needs: [pack-and-release]
    if: always() && !failure() && !cancelled() && inputs.deploy_method == 'terraform'
    uses: ./.github/workflows/terraform_apply.yaml
    with:
      terraform_dir: ${{ inputs.terraform_dir }}
      terraform_github_repo: ${{ inputs.terraform_github_repo }}
      vault_model_name: ${{ inputs.vault_model_name }}
      iam_group: ${{ inputs.iam_group }}
      environment: ${{ inputs.environment }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      TERRAFORM_REPO_SSH_KEY: ${{ secrets.TERRAFORM_REPO_SSH_KEY }}
