name: Deploy

on:
  workflow_call:
    inputs:
      charm_name:
        required: true
        type: string
      channel:
        required: true
        type: string
      juju_controller_name:
        required: false
        type: string
      juju_model_name:
        required: false
        type: string
      deploy_method:
        required: false
        default: 'juju'
        type: string
      terraform_dir:
        required: false
        default: ''
        type: string
      environment:
        required: false
        default: ''
        type: string
      environment_url:
        required: false
        default: ''
        type: string

    secrets:
      VAULT_APPROLE_ROLE_ID:
        required: true
      VAULT_APPROLE_SECRET_ID:
        required: true
      CHARMHUB_TOKEN:
        required: true

jobs:
  setup:
    name: Set up
    outputs:
      juju_controller_name: ${{ steps.setup-vars.outputs.juju_controller_name }}
      juju_model_name: ${{ steps.setup-vars.outputs.juju_model_name }}
    steps:
      - name: Set up vars
        id: setup-vars
        run: |
          export JUJU_CONTROLLER_NAME_INPUT=${{ inputs.juju_controller_name }}
          export JUJU_MODEL_NAME_INPUT=${{ inputs.juju_model_name }}
          echo "juju_controller_name=${JUJU_CONTROLLER_NAME_INPUT:-${{ vars.JUJU_CONTROLLER_NAME }}}" >> $GITHUB_OUTPUT
          echo "juju_model_name=${JUJU_MODEL_NAME_INPUT:-${{ vars.JUJU_MODEL_NAME }}}" >> $GITHUB_OUTPUT

  pack-and-release:
    name: Pack and Release
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/pack-release.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      environment: ${{ inputs.environment }}
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

  deploy-ps6:
    name: Deploy to PS6 Environment
    needs: [setup, pack-and-release]
    if: always() && !failure() && !cancelled() && inputs.deploy_method == 'juju'
    uses: ./.github/workflows/juju-deploy-ps6.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      resource_name: ${{ needs.publish-image-and-release-charm.outputs.resource_name }}
      resource_revision_number: ${{ needs.publish-image-and-release-charm.outputs.resource_revision_number }}
      juju_controller_name: ${{ needs.setup.outputs.juju_controller_name }}
      juju_model_name: ${{ needs.setup.outputs.juju_model_name }}
      environment: ${{ inputs.environment }}
      environment_url: ${{ inputs.environment_url }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  deploy-ps7:
    name: Deploy to PS7 Environment
    needs: [pack-and-release]
    if: always() && !failure() && !cancelled() && inputs.deploy_method == 'terraform'
    uses: ./.github/workflows/terraform-deploy-ps7.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      terraform_dir: ${{ inputs.terraform_dir }}
      revision_number: ${{ needs.publish-image-and-release-charm.outputs.revision_number }}
      resource_name: ${{ needs.publish-image-and-release-charm.outputs.resource_name }}
      resource_revision_number: ${{ needs.publish-image-and-release-charm.outputs.resource_revision_number }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
